version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - sudo su
      - sudo apt-get update -y

  pre_build:
    commands:
      - echo "Running pre-build tasks..."

  build:
    commands:
      - echo "Building the application..."
      - grep -Fq "Congratulations" index.html

  post_build:
    commands:
      - echo "Running post-build tasks..."

artifacts:
  files:
    - '**/*'
  discard-paths: no
